name: 01-building-blocks
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello world"
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"
